# Generated by Django 5.2.1 on 2025-12-20 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('new', 'New Arrivals'), ('basketball', 'Basketball'), ('running', 'Running'), ('trending', 'Trending'), ('sale', 'Sale'), ('casual', 'Casual'), ('lifestyle', 'Lifestyle')], default='new', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='brt.product')),
            ],
            options={
                'ordering': ['order', '-is_primary'],
            },
        ),
    ]
