# Generated by Django 5.2.1 on 2025-12-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brt', '0002_remove_product_image_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=67420, help_text='Starting price for display', max_digits=10),
        ),
        migrations.AddField(
            model_name='productsize',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for this specific size', max_digits=10),
        ),
    ]
