# Generated by Django 5.2.1 on 2025-12-20 08:25

import brt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brt', '0003_remove_product_price_product_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=brt.models.product_image_path),
        ),
    ]
