# Generated by Django 5.2.1 on 2025-12-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brt', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Leave at 0 to use base price', max_digits=10),
        ),
    ]
